#!/usr/bin/env bash
# FairLens Council Runner
# Usage:
#   ./council/run_council.sh                    # Full council session
#   ./council/run_council.sh --persona sentinel  # Single persona
#   ./council/run_council.sh --list              # List personas

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
REPORTS_DIR="$SCRIPT_DIR/reports"
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")

mkdir -p "$REPORTS_DIR"

# Persona mapping
declare -A PERSONAS=(
    [atlas]="architect.md"
    [meridian]="product_strategist.md"
    [forge]="revenue_engineer.md"
    [vector]="growth_hacker.md"
    [patent]="ip_counsel.md"
    [sentinel]="qa_guardian.md"
    [nexus]="orchestrator.md"
)

declare -A PERSONA_NAMES=(
    [atlas]="Chief Architect"
    [meridian]="Product Strategist"
    [forge]="Revenue Engineer"
    [vector]="Growth Hacker"
    [patent]="IP Counsel"
    [sentinel]="QA Guardian"
    [nexus]="Council Orchestrator"
)

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

usage() {
    echo "FairLens Council Runner"
    echo ""
    echo "Usage:"
    echo "  $0                         Run full council session"
    echo "  $0 --persona <name>        Run a specific persona"
    echo "  $0 --list                  List available personas"
    echo "  $0 --help                  Show this help"
    echo ""
    echo "Personas: atlas, meridian, forge, vector, patent, sentinel, nexus"
}

list_personas() {
    echo -e "${BLUE}FairLens Council Personas${NC}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    for key in atlas meridian forge vector patent sentinel nexus; do
        printf "  %-12s %s\n" "$key" "${PERSONA_NAMES[$key]}"
    done
}

run_persona() {
    local persona_key="$1"
    local persona_file="${PERSONAS[$persona_key]}"
    local persona_name="${PERSONA_NAMES[$persona_key]}"
    local report_file="$REPORTS_DIR/${persona_key}_${TIMESTAMP}.md"
    local prompt_file="$SCRIPT_DIR/$persona_file"

    if [[ ! -f "$prompt_file" ]]; then
        echo "Error: Persona file not found: $prompt_file"
        return 1
    fi

    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}Running: ${persona_name} (${persona_key})${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"

    local prompt
    prompt=$(cat "$prompt_file")

    # Run Claude with the persona prompt against the project
    claude --print \
        "You are analyzing the FairLens API project at ${PROJECT_DIR}. Read the codebase thoroughly, then execute your role as described below. Produce a complete, actionable report.

${prompt}

Start by reading the key files in the project (app/main.py, app/services/bias_detector.py, app/services/dataset_analyzer.py, app/api/analysis.py, app/api/billing.py, app/core/auth.py, app/models/schemas.py, requirements.txt) and then produce your full analysis report." \
        > "$report_file" 2>/dev/null || {
            echo -e "${YELLOW}Warning: Claude execution returned non-zero. Check report for details.${NC}"
        }

    echo -e "Report saved: ${report_file}"
    echo ""
}

run_full_council() {
    local summary_file="$REPORTS_DIR/council_session_${TIMESTAMP}.md"

    echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║     FairLens Council Session             ║${NC}"
    echo -e "${GREEN}║     ${TIMESTAMP}                  ║${NC}"
    echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"
    echo ""

    # Run in council order (per orchestrator protocol)
    local order=(sentinel atlas meridian forge vector patent)

    for persona in "${order[@]}"; do
        run_persona "$persona"
    done

    # Run orchestrator last to synthesize
    echo -e "${YELLOW}Running Nexus to synthesize all findings...${NC}"

    # Collect all reports from this session
    local all_reports=""
    for persona in "${order[@]}"; do
        local report="$REPORTS_DIR/${persona}_${TIMESTAMP}.md"
        if [[ -f "$report" ]]; then
            all_reports+="
## ${PERSONA_NAMES[$persona]} Report
$(cat "$report")
---
"
        fi
    done

    # Run Nexus with all reports as context
    claude --print \
        "You are Nexus, the Council Orchestrator for FairLens API. The following reports were just generated by each council member. Synthesize them into a unified action plan following the format in your protocol.

${all_reports}

$(cat "$SCRIPT_DIR/orchestrator.md")

Produce the final Council Action Plan." \
        > "$summary_file" 2>/dev/null || true

    echo -e "${GREEN}╔══════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║     Council Session Complete             ║${NC}"
    echo -e "${GREEN}╚══════════════════════════════════════════╝${NC}"
    echo ""
    echo "Session summary: $summary_file"
    echo "All reports: $REPORTS_DIR/*_${TIMESTAMP}.md"
}

# Parse arguments
case "${1:-}" in
    --persona)
        if [[ -z "${2:-}" ]]; then
            echo "Error: --persona requires a name"
            usage
            exit 1
        fi
        if [[ -z "${PERSONAS[${2}]+x}" ]]; then
            echo "Error: Unknown persona '${2}'"
            list_personas
            exit 1
        fi
        run_persona "$2"
        ;;
    --list)
        list_personas
        ;;
    --help|-h)
        usage
        ;;
    "")
        run_full_council
        ;;
    *)
        echo "Unknown option: $1"
        usage
        exit 1
        ;;
esac
